# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Tianhong Xie's Portfolio # This is what shows up in the tab of the browser



# Hero Section
name: Tianhong Xie
headline: 
description: >- # dont remove this line. this will ignore all new lines until the next section
  Third-year engineering student at Harvey Mudd College, California. I focus on firmware/embedded system design, 
  low-level processor validation and also some machine learning. 

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/tian.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
# resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing # or /assets/resume/resume.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: tian-xie-11404220a/    # https://www.linkedin.com/in/{your url slug} 
  github:    # https://github.com/{your url slug} 
  stackoverflow:      # https://stackoverflow.com/users/{your url slug}
  medium:            # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Firmware / Embedded Systems
    tools:
    - C / C++
    - Bare-metal programming
    - ZephyrRTOS
    - ARM Cortex-M, RISC-V
    - SPI / I2C / UART / CAN
    - DMA / Interrupts / Timers
    - Analog / Digital Filter Design
    - Signal Processing / Fourier Transform
    - STM32 / Raspberry Pi
    - JTAG
  - category: Machine Learning
    tools:
    - Python
    - PyTorch
    - Model training & fine-tuning
    - CNNs / VAEs / Autoencoders
    - LoRA / PEFT
    - Edge ML / TinyML
    - Model compression
    - Computer Vision
    - Dataset curation & evaluation
  - category: RISC-V Processor Verification
    tools:
    - C++
    - Physical Memory Protection unit (PMP)
    - Debug module
    - Test plan / coverage points
    - RISC-V
    - OpenOCD / JTAG


# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#2d2926"
  border: "#f7f3e3"
  link: "#ffc94d"
  highlight: "#ffb800"
  background: "#fffdf5"
  light_background: "#fff9e6"

# A few examples. 
basic theme:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"
  
  mint theme:
  text: "#2c3333"
  border: "#e0f2ef"
  link: "#40b3a2"
  highlight: "#2a9d8f"
  background: "#f7fbfa"
  light_background: "#f0f9f7"
  
lemon theme:

  
  pink theme:
  text: "#2d2d2d"
  border: "#f8e2e2"
  link: "#ff8fa3"
  highlight: "#ff4d6d"
  background: "#fff8f8"
  light_background: "#fff5f6"






#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
